# Generated by Django 2.2.3 on 2019-07-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type_meeting', models.CharField(choices=[('', '---------'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='', max_length=255)),
                ('state', models.BooleanField(default=True, editable=False)),
                ('sub_state', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('point_state', models.CharField(choices=[('pending', 'pending'), ('executed', 'executed')], default='pending', max_length=255)),
                ('state', models.BooleanField(default=True, editable=False)),
                ('sub_state', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting')),
            ],
            options={
                'verbose_name': 'point',
                'verbose_name_plural': 'points',
                'ordering': ('created_at',),
            },
        ),
    ]
