# Generated by Django 2.2.3 on 2019-07-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='comments',
            field=models.TextField(),
        ),
    ]
