# Generated by Django 2.2.3 on 2019-07-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_code', models.CharField(max_length=255, unique=True)),
                ('supervendor_code', models.CharField(max_length=255)),
                ('material_description', models.CharField(blank=True, max_length=255, null=True)),
                ('unity', models.CharField(blank=True, choices=[('', '---------'), ('und', 'und'), ('pcs', 'pcs'), ('mts', 'mts')], max_length=255, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('state', models.BooleanField(default=True, editable=False)),
                ('sub_state', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hardware',
                'verbose_name_plural': 'hardware',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='HardwareCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('state', models.BooleanField(default=True, editable=False)),
                ('sub_state', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hardware category',
                'verbose_name_plural': 'hardware categories',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='HardwareControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, editable=False)),
                ('hardware_state', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Site', 'Site'), ('Failure', 'Failure')], default='Warehouse', max_length=255)),
                ('state', models.BooleanField(default=True, editable=False)),
                ('sub_state', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Hardware')),
            ],
            options={
                'verbose_name': 'hardware control',
                'verbose_name_plural': 'hardware controls',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='HardwareControlLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, editable=False)),
                ('hardware_state', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Site', 'Site'), ('Failure', 'Failure')], default='Warehouse', max_length=255)),
                ('state', models.BooleanField(default=True, editable=False)),
                ('sub_state', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Hardware')),
                ('hardware_control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hardware.HardwareControl')),
            ],
            options={
                'verbose_name': 'hardware control log',
                'verbose_name_plural': 'hardware control log',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='hardware',
            name='hardware_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.HardwareCategory'),
        ),
    ]
