# Generated by Django 2.2.3 on 2019-07-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarecontrol',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hardwarecontrollog',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
