# Generated by Django 2.2.3 on 2019-07-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20190726_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarecontrol',
            name='active_avantel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hardwarecontrol',
            name='state_avantel',
            field=models.CharField(choices=[('', '---------'), ('new', 'new'), ('used', 'used')], default='', max_length=255),
        ),
    ]
