# Generated by Django 2.2.3 on 2019-07-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('file1', models.FileField(blank=True, null=True, upload_to='sites/<django.db.models.fields.CharField>/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='sites/<django.db.models.fields.CharField>/')),
                ('file3', models.FileField(blank=True, null=True, upload_to='sites/<django.db.models.fields.CharField>/')),
                ('file4', models.FileField(blank=True, null=True, upload_to='sites/<django.db.models.fields.CharField>/')),
                ('file5', models.FileField(blank=True, null=True, upload_to='sites/<django.db.models.fields.CharField>/')),
                ('state', models.BooleanField(default=True, editable=False)),
                ('sub_state', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'ordering': ('created_at',),
            },
        ),
    ]
