# Generated by Django 2.2.3 on 2019-07-29 02:31

from django.db import migrations, models
import sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=sites.models.site_name_str),
        ),
        migrations.AlterField(
            model_name='site',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=sites.models.site_name_str),
        ),
        migrations.AlterField(
            model_name='site',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=sites.models.site_name_str),
        ),
        migrations.AlterField(
            model_name='site',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to=sites.models.site_name_str),
        ),
        migrations.AlterField(
            model_name='site',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to=sites.models.site_name_str),
        ),
    ]
