# Generated by Django 2.2.3 on 2019-07-29 23:30

from django.db import migrations, models
import sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190729_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='file6',
            field=models.FileField(blank=True, null=True, upload_to=sites.models.site_name_str),
        ),
        migrations.AddField(
            model_name='site',
            name='file7',
            field=models.FileField(blank=True, null=True, upload_to=sites.models.site_name_str),
        ),
    ]
